### ISSUE TITLE
Flutter runner multiple windows

### ISSUE THREAD

**Issue by kirill-21** [timsneath/win32#357]
Hi, i've found this pull request(https://github.com/timsneath/win32/pull/287) in this repository and want to ask why didn't you add this functionally and closed the request? It seems to be the only easy-to-use solution for multiple windows on Windows platform, there aren't any packages or official solutions for this task from flutter team (except of course creating a whole separate app and spawning it as a child window of the current process)

**Comment by timsneath** [comment]
Hi there! It looks like it lives on here: https://github.com/ilopX/win

After chatting with @ilopX, we aligned on the general philosophy that it was better to keep the low-level win32 package separate from any potential higher-level idiomatic wrapper libraries. That lets those packages evolve at their own pace and experiment without worrying about API changes breaking semver, and also keeps win32 smaller and more focused than it would otherwise be. 

It looks like this work continues here: https://github.com/ilopX/win

I'm also taking a similar approach, for example: https://github.com/timsneath/win32_registry, which provides a high-level class wrapper over the underlying win32 registry APIs. I've also been experimenting a little with a Dart runner for Flutter apps, which is here: https://github.com/timsneath/win32_runner. 

Hopefully over time there will be a growing collection of win32_* libraries that wrap win32 with higher-level alternatives that are well-suited for Dart developers to use without requiring any knowledge of FFI or C.

**Comment by kirill-21** [comment]
> Hi there! It looks like it lives on here: https://github.com/ilopX/win
> 
> After chatting with @ilopX, we aligned on the general philosophy that it was better to keep the low-level win32 package separate from any potential higher-level idiomatic wrapper libraries. That lets those packages evolve at their own pace and experiment without worrying about API changes breaking semver, and also keeps win32 smaller and more focused than it would otherwise be.
> 
> I'm also taking a similar approach, for example: https://github.com/timsneath/win32_registry, which provides a high-level class wrapper over the underlying win32 registry APIs. I've also been experimenting a little with a Dart runner for Flutter apps, which is here: https://github.com/timsneath/win32_runner, although mine is designed more as a one-to-one replacement of the Flutter C++ runner, rather than adding new features like multiple windows.
> 
> Hopefully over time there will be a growing collection of win32_* libraries that wrap win32 with higher-level alternatives that are well-suited for Dart developers to use without requiring any knowledge of FFI or C.

The problem is that his package is already outdated
